name: Storymachine
favicon: null
layout_spectrum: 0.80541
typography_spectrum: 0
title: 'Storymachine: Creative Wargaming'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#281402'
    - '#808080'
    - '#fdf6ad'
    - '#8ad8f5'
    - '#e6b006'
  brandStrength: 0.5
  lightness: 0.625
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
